// Card Data
export const CardData = [
  {
    id: 1,
    img: "https://i.ibb.co/ygm6Cb6/product1.webp",
    name: "Floral Mini with Camisole",
    price: 130,
  },
  {
    id: 2,
    img: "https://i.ibb.co/0qqbRHY/product2.webp",
    name: "Jeans & Tee full sleeves",
    price: 250,
  },
  {
    id: 3,
    img: "https://i.ibb.co/vXCVRHG/product3.webp",
    name: "Jeggings",
    price: 99,
  },
  {
    id: 4,
    img: "https://i.ibb.co/HBZ3XBh/product4.webp",
    name: "Off Shoulder Skater Dress",
    price: 80,
    rating: `<i className="fa empty fa-star" aria-hidden="true"></i>`,
  },
  {
    id: 5,
    img: "https://i.ibb.co/7vKtkt8/product12.webp",
    name: "Jeans & Sweater Combo",
    price: 150,
    rating: `<i className="fa empty fa-star" aria-hidden="true"></i>`,
  },
  {
    id: 6,
    img: "https://i.ibb.co/XjVy54X/product14.webp",
    name: "Jeans & Tees",
    price: 78,
  },
  {
    id: 7,
    img: "https://i.ibb.co/gVmM7T8/product13.webp",
    name: "Jeggings & Crop Cami Top",
    price: 65,
  },
  {
    id: 8,
    img: "https://i.ibb.co/4Rh8Wy8/product7.webp",
    name: "Skin tight Jeans & Tees",
    price: 50,
    rating: `<i className="fa empty fa-star" aria-hidden="true"></i>`,
  },
];

// Card Data 2
export const CardData2 = [
  {
    id: 1,
    img: "https://i.ibb.co/7kY84xm/1-1.webp",
    name: "Skin Tight Jeans",
    price: 30,
  },
  {
    id: 2,
    img: "https://i.ibb.co/j5pRc76/1-2.webp",
    name: "Cross Body Handbag",
    price: 25,
  },
  {
    id: 3,
    img: "https://i.ibb.co/0qCBws7/1-3.webp",
    name: "Open Toe Stiletto",
    price: 99,
  },
  {
    id: 4,
    img: " https://i.ibb.co/bdYMQfz/1-5.webp",
    name: "Cross Handbag",
    price: 75,
  },
  {
    id: 5,
    img: "https://i.ibb.co/vXCVRHG/product3.webp",
    name: "Tree FUll sleeves",
    price: 62,
  },
  {
    id: 6,
    img: "https://i.ibb.co/sg2WCm7/1-4.webp",
    name: "Handbags",
    price: 50,
  },
];

// Clothing Data
export const ClothingData = [
  {
    id: 1,
    img1: "https://i.ibb.co/nbFdsSZ/clothing1.webp",
    img2: "https://i.ibb.co/zxH348R/clothing2.webp",
    img3: "https://i.ibb.co/PwtZK73/clothing3.webp",
    name: "Floral Mini with Camisole",
    price: "438.00",
    des: "Nam tempus turpis at metus scelerisque placerat nulla deumantos solicitud felis. Pellentesque diam dolor, elementum etos lobortis des mollis ut risus. Sedcus faucibus an sullamcorper mattis drostique des commodo pharetras loremos.Donec pretium egestas sapien et mollis. Sample Unordered List Comodous in tempor ullamcorper miaculis Pellentesque vitae neque mollis urna mattis...",
    brand: "Shein",
    movement: "Shorts",
    availability: "In Stock",
  },
  {
    id: 2,
    img1: "https://i.ibb.co/8Kgxm03/clothing4.webp",
    img2: "https://i.ibb.co/B3CLbD9/clothing5.webp",
    img3: "https://i.ibb.co/nD98Y7p/clothing6.webp",
    name: "Jeans & Tee full sleeves",
    price: "789.00",
    des: "Nam tempus turpis at metus scelerisque placerat nulla deumantos solicitud felis. Pellentesque diam dolor, elementum etos lobortis des mollis ut risus. Sedcus faucibus an sullamcorper mattis drostique des commodo pharetras loremos.Donec pretium egestas sapien et mollis. Sample Unordered List Comodous in tempor ullamcorper miaculis Pellentesque vitae neque mollis urna mattis...",
    brand: "Salvatore",
    movement: "T-Shirt",
    availability: "In Stock",
  },
  {
    id: 3,
    img1: "https://i.ibb.co/KFN7zLx/clothing7.webp",
    img2: "https://i.ibb.co/1dcqHDG/clothing8.webp",
    img3: "https://i.ibb.co/jfDxZqy/clothing9.webp",
    name: "Jeggings",
    price: "520.00",
    des: "Nam tempus turpis at metus scelerisque placerat nulla deumantos solicitud felis. Pellentesque diam dolor, elementum etos lobortis des mollis ut risus. Sedcus faucibus an sullamcorper mattis drostique des commodo pharetras loremos.Donec pretium egestas sapien et mollis. Sample Unordered List Comodous in tempor ullamcorper miaculis Pellentesque vitae neque mollis urna mattis...",
    brand: "Western Dress",
    movement: "StalkBuyLove",
    availability: "In Stock",
  },
  {
    id: 4,
    img1: "https://i.ibb.co/s1R2TPr/clothing10.webp",
    img2: "https://i.ibb.co/T81WM3N/clothing11.webp",
    img3: "https://i.ibb.co/kS4RqVz/clothing12.webp",
    name: "Off Shoulder Skater Dress",
    price: "350.00",
    des: "Nam tempus turpis at metus scelerisque placerat nulla deumantos solicitud felis. Pellentesque diam dolor, elementum etos lobortis des mollis ut risus. Sedcus faucibus an sullamcorper mattis drostique des commodo pharetras loremos.Donec pretium egestas sapien et mollis. Sample Unordered List Comodous in tempor ullamcorper miaculis Pellentesque vitae neque mollis urna mattis...",
    brand: "StalkBuyLove",
    movement: "Frock",
    availability: "In Stock",
  },

  {
    id: 5,
    img1: "  https://i.ibb.co/RyDzQRN/clothing13.webp",
    img2: " https://i.ibb.co/4Jv3jdP/clothing14.webp",
    img3: "https://i.ibb.co/7R4hkr3/clothing15.webp",
    name: "Jeans & Sweater Combo",
    price: "400.00",
    des: "Nam tempus turpis at metus scelerisque placerat nulla deumantos solicitud felis. Pellentesque diam dolor, elementum etos lobortis des mollis ut risus. Sedcus faucibus an sullamcorper mattis drostique des commodo pharetras loremos.Donec pretium egestas sapien et mollis. Sample Unordered List Comodous in tempor ullamcorper miaculis Pellentesque vitae neque mollis urna mattis...",
    brand: "Aerosoles",
    movement: "Jeans",
    availability: "In Stock",
  },
  {
    id: 6,
    img1: "https://i.ibb.co/dmdsQCD/clothing16.webp",
    img2: "https://i.ibb.co/1dcqHDG/clothing8.webp",
    img3: "https://i.ibb.co/nD98Y7p/clothing6.webp",
    name: "Jeans & Tees",
    price: "529.00",
    des: "Nam tempus turpis at metus scelerisque placerat nulla deumantos solicitud felis. Pellentesque diam dolor, elementum etos lobortis des mollis ut risus. Sedcus faucibus an sullamcorper mattis drostique des commodo pharetras loremos.Donec pretium egestas sapien et mollis. Sample Unordered List Comodous in tempor ullamcorper miaculis Pellentesque vitae neque mollis urna mattis...",
    brand: "Shoping Mall In USA",
    movement: "Jeans & Tees",
    availability: "In Stock",
  },
  {
    id: 7,
    img1: "https://i.ibb.co/1dcqHDG/clothing8.webp",
    img2: "https://i.ibb.co/KFN7zLx/clothing7.webp",
    img3: "https://i.ibb.co/zxH348R/clothing2.webp",
    name: "Jeggings & Crop Cami Top",
    price: "419.00",
    des: "Nam tempus turpis at metus scelerisque placerat nulla deumantos solicitud felis. Pellentesque diam dolor, elementum etos lobortis des mollis ut risus. Sedcus faucibus an sullamcorper mattis drostique des commodo pharetras loremos.Donec pretium egestas sapien et mollis. Sample Unordered List Comodous in tempor ullamcorper miaculis Pellentesque vitae neque mollis urna mattis...",
    brand: "Shein",
    movement: "Sleeveless Tops",
    availability: "In Stock",
  },
  {
    id: 8,
    img1: "https://i.ibb.co/jfDxZqy/clothing9.webp",
    img2: "https://i.ibb.co/nbFdsSZ/clothing1.webp",
    img3: "https://i.ibb.co/PwtZK73/clothing3.webp",
    name: "Skin tight Jeans & Tees",
    price: "740",
    des: "Nam tempus turpis at metus scelerisque placerat nulla deumantos solicitud felis. Pellentesque diam dolor, elementum etos lobortis des mollis ut risus. Sedcus faucibus an sullamcorper mattis drostique des commodo pharetras loremos.Donec pretium egestas sapien et mollis. Sample Unordered List Comodous in tempor ullamcorper miaculis Pellentesque vitae neque mollis urna mattis...",
    brand: "Gucci",
    movement: "Western Dress",
    availability: "In Stock",
  },
];

// Handbags Data
export const HandbagsData = [
  {
    id: 1,
    img1: "https://i.ibb.co/n78cj9d/handbags11.webp",
    img2: "https://i.ibb.co/pfdKq5D/handbags9.webp",
    img3: "https://i.ibb.co/zRbQHk4/handbags3.webp",
    name: "Vestibulum dapibus nunc ac augue nibh",
    price: "37.00",
    des: "Nam tempus turpis at metus scelerisque placerat nulla deumantos solicitud felis. Pellentesque diam dolor, elementum etos lobortis des mollis ut risus. Sedcus faucibus an sullamcorper mattis drostique des commodo pharetras loremos.Donec pretium egestas sapien et mollis. Sample Unordered List Comodous in tempor ullamcorper miaculis Pellentesque vitae neque mollis urna mattis...",
    brand: "home3",
    movement: "Amazon",
    availability: "Many In Stock",
  },

  {
    id: 2,
    img1: "https://i.ibb.co/rbXvdJy/handbags10.webp",
    img2: "https://i.ibb.co/pdz19VJ/handbags5.webp",
    img3: "https://i.ibb.co/6HsLY6N/handbags2.webp",
    name: "Handbag",
    price: "34.00",
    des: "Nam tempus turpis at metus scelerisque placerat nulla deumantos solicitud felis. Pellentesque diam dolor, elementum etos lobortis des mollis ut risus. Sedcus faucibus an sullamcorper mattis drostique des commodo pharetras loremos.Donec pretium egestas sapien et mollis. Sample Unordered List Comodous in tempor ullamcorper miaculis Pellentesque vitae neque mollis urna mattis...",
    brand: "Furnicom",
    movement: "Amazon",
    availability: "In Stock",
  },
  {
    id: 3,
    img1: "https://i.ibb.co/D5TrqqF/handbags8.webp",
    img2: "https://i.ibb.co/MDXyKyF/handbags7.webp",
    img3: "https://i.ibb.co/yRK9s5R/handbags4.webp",
    name: "Flap Satchel Bag",
    price: "99.00",
    des: "Nam tempus turpis at metus scelerisque placerat nulla deumantos solicitud felis. Pellentesque diam dolor, elementum etos lobortis des mollis ut risus. Sedcus faucibus an sullamcorper mattis drostique des commodo pharetras loremos.Donec pretium egestas sapien et mollis. Sample Unordered List Comodous in tempor ullamcorper miaculis Pellentesque vitae neque mollis urna mattis...",
    brand: "Salvatore",
    movement: "Hand Bags",
    availability: "In Stock",
  },
  {
    id: 4,
    img1: "https://i.ibb.co/1sZWJSX/handbags1.jpg",
    img2: "https://i.ibb.co/CQ00dTn/handbags15.webp",
    img3: "https://i.ibb.co/StN8hnN/handbags14.webp",
    name: "Shoulder Strap Handbags",
    price: "45.00",
    des: "Nam tempus turpis at metus scelerisque placerat nulla deumantos solicitud felis. Pellentesque diam dolor, elementum etos lobortis des mollis ut risus. Sedcus faucibus an sullamcorper mattis drostique des commodo pharetras loremos.Donec pretium egestas sapien et mollis. Sample Unordered List Comodous in tempor ullamcorper miaculis Pellentesque vitae neque mollis urna mattis...",
    brand: "Salvatore",
    movement: "Bags",
    availability: "In Stock",
  },

  {
    id: 5,
    img1: "https://i.ibb.co/7k7t509/handbags13.webp",
    img2: "https://i.ibb.co/hyzc1JQ/handbags12.webp",
    img3: "https://i.ibb.co/n78cj9d/handbags11.webp",
    name: "Metallic Detail Handbag",
    price: "85.00",
    des: "Nam tempus turpis at metus scelerisque placerat nulla deumantos solicitud felis. Pellentesque diam dolor, elementum etos lobortis des mollis ut risus. Sedcus faucibus an sullamcorper mattis drostique des commodo pharetras loremos.Donec pretium egestas sapien et mollis. Sample Unordered List Comodous in tempor ullamcorper miaculis Pellentesque vitae neque mollis urna mattis...",
    brand: "Lifestyle",
    movement: "Hand Bag",
    availability: "In Stock",
  },
  {
    id: 6,
    img1: "https://i.ibb.co/MDXyKyF/handbags7.webp",
    img2: "https://i.ibb.co/pfdKq5D/handbags9.webp",
    img3: "https://i.ibb.co/1sZWJSX/handbags1.jpg",
    name: "Flap Satchel Bag",
    price: "67.00",
    des: "Nam tempus turpis at metus scelerisque placerat nulla deumantos solicitud felis. Pellentesque diam dolor, elementum etos lobortis des mollis ut risus. Sedcus faucibus an sullamcorper mattis drostique des commodo pharetras loremos.Donec pretium egestas sapien et mollis. Sample Unordered List Comodous in tempor ullamcorper miaculis Pellentesque vitae neque mollis urna mattis...",
    brand: "Lifestyle",
    movement: "Hand Bag",
    availability: "In Stock",
  },
  {
    id: 7,
    img1: "https://i.ibb.co/7k7t509/handbags13.webp",
    img2: "https://i.ibb.co/6HsLY6N/handbags2.webp",
    img3: "https://i.ibb.co/MDXyKyF/handbags7.webp",
    name: "Cross Body Handbag",
    price: "75.00",
    des: "Nam tempus turpis at metus scelerisque placerat nulla deumantos solicitud felis. Pellentesque diam dolor, elementum etos lobortis des mollis ut risus. Sedcus faucibus an sullamcorper mattis drostique des commodo pharetras loremos.Donec pretium egestas sapien et mollis. Sample Unordered List Comodous in tempor ullamcorper miaculis Pellentesque vitae neque mollis urna mattis...",
    brand: "Lifestyle",
    movement: "Bags",
    availability: "In Stock",
  },
  {
    id: 8,
    img1: "https://i.ibb.co/MDXyKyF/handbags7.webp",
    img2: "https://i.ibb.co/rbXvdJy/handbags10.webp",
    img3: "https://i.ibb.co/pdz19VJ/handbags5.webp",
    name: "Handbags",
    price: "84.00",
    des: "Nam tempus turpis at metus scelerisque placerat nulla deumantos solicitud felis. Pellentesque diam dolor, elementum etos lobortis des mollis ut risus. Sedcus faucibus an sullamcorper mattis drostique des commodo pharetras loremos.Donec pretium egestas sapien et mollis. Sample Unordered List Comodous in tempor ullamcorper miaculis Pellentesque vitae neque mollis urna mattis...",
    brand: "Gucci",
    movement: "Hand Bag",
    availability: "In Stock",
  },
];

// Sandals Data
export const SandalsData = [
  {
    id: 1,
    img1: "https://i.ibb.co/Kbfw5YB/sandals11.webp",
    img2: "https://i.ibb.co/6y5Y4rb/sandals9.webp",
    img3: "https://i.ibb.co/6y5Y4rb/sandals9.webp",
    name: "Artifical Leather Sandals",
    price: "37.00",
    des: "Nam tempus turpis at metus scelerisque placerat nulla deumantos solicitud felis. Pellentesque diam dolor, elementum etos lobortis des mollis ut risus. Sedcus faucibus an sullamcorper mattis drostique des commodo pharetras loremos.Donec pretium egestas sapien et mollis. Sample Unordered List Comodous in tempor ullamcorper miaculis Pellentesque vitae neque mollis urna mattis...",
    brand: "Aerosoles",
    movement: "High Heel",
    availability: "Many In Stock",
  },
  {
    id: 2,
    img1: "https://i.ibb.co/2jHvLH1/sandals8.webp",
    img2: "https://i.ibb.co/728P9fk/sandals15.webp",
    img3: "https://i.ibb.co/VqhMcBt/sandals10.webp",
    name: "Black Leather Shoes",
    price: "34.00",
    des: "Nam tempus turpis at metus scelerisque placerat nulla deumantos solicitud felis. Pellentesque diam dolor, elementum etos lobortis des mollis ut risus. Sedcus faucibus an sullamcorper mattis drostique des commodo pharetras loremos.Donec pretium egestas sapien et mollis. Sample Unordered List Comodous in tempor ullamcorper miaculis Pellentesque vitae neque mollis urna mattis...",
    brand: "Aerosoles",
    movement: "High Heel",
    availability: "In Stock",
  },
  {
    id: 3,
    img1: "https://i.ibb.co/p2Xvg9P/sandals3.webp",
    img2: "https://i.ibb.co/T0Mzjyk/sandals13.webp",
    img3: "https://i.ibb.co/728P9fk/sandals15.webp",
    name: "Mistro Heel Sandal",
    price: "99.00",
    des: "Nam tempus turpis at metus scelerisque placerat nulla deumantos solicitud felis. Pellentesque diam dolor, elementum etos lobortis des mollis ut risus. Sedcus faucibus an sullamcorper mattis drostique des commodo pharetras loremos.Donec pretium egestas sapien et mollis. Sample Unordered List Comodous in tempor ullamcorper miaculis Pellentesque vitae neque mollis urna mattis...",
    brand: "Aerosoles",
    movement: "High Heel",
    availability: "In Stock",
  },
  {
    id: 4,
    img1: "https://i.ibb.co/DbrHM62/sandals6.webp",
    img2: "https://i.ibb.co/2Fg3MYy/sandals5.webp",
    img3: "https://i.ibb.co/2Fg3MYy/sandals5.webp",
    name: "Peep Toe Stilettos",
    price: "45.00",
    des: "Nam tempus turpis at metus scelerisque placerat nulla deumantos solicitud felis. Pellentesque diam dolor, elementum etos lobortis des mollis ut risus. Sedcus faucibus an sullamcorper mattis drostique des commodo pharetras loremos.Donec pretium egestas sapien et mollis. Sample Unordered List Comodous in tempor ullamcorper miaculis Pellentesque vitae neque mollis urna mattis...",
    brand: "Aerosoles",
    movement: "High Heel",
    availability: "In Stock",
  },

  {
    id: 5,
    img1: "https://i.ibb.co/Nm46235/sandals4.webp",
    img2: "https://i.ibb.co/2Fg3MYy/sandals5.webp",
    img3: "https://i.ibb.co/VqhMcBt/sandals10.webp",
    name: "Black Leather Shoes",
    price: "85.00",
    des: "Nam tempus turpis at metus scelerisque placerat nulla deumantos solicitud felis. Pellentesque diam dolor, elementum etos lobortis des mollis ut risus. Sedcus faucibus an sullamcorper mattis drostique des commodo pharetras loremos.Donec pretium egestas sapien et mollis. Sample Unordered List Comodous in tempor ullamcorper miaculis Pellentesque vitae neque mollis urna mattis...",
    brand: "Aerosoles",
    movement: "High Heel",
    availability: "In Stock",
  },
  {
    id: 6,
    img1: "https://i.ibb.co/728P9fk/sandals15.webp",
    img2: "https://i.ibb.co/Kbfw5YB/sandals11.webp",
    img3: "https://i.ibb.co/6y5Y4rb/sandals9.webp",
    name: "High Heel Sandals",
    price: "67.00",
    des: "Nam tempus turpis at metus scelerisque placerat nulla deumantos solicitud felis. Pellentesque diam dolor, elementum etos lobortis des mollis ut risus. Sedcus faucibus an sullamcorper mattis drostique des commodo pharetras loremos.Donec pretium egestas sapien et mollis. Sample Unordered List Comodous in tempor ullamcorper miaculis Pellentesque vitae neque mollis urna mattis...",
    brand: "Aerosoles",
    movement: "High Heel",
    availability: "In Stock",
  },
  {
    id: 7,
    img1: "https://i.ibb.co/Nm46235/sandals4.webp",
    img2: "https://i.ibb.co/p2Xvg9P/sandals3.webp",
    img3: "https://i.ibb.co/2Fg3MYy/sandals5.webp",
    name: "Open Toe Stiletto",
    price: "75.00",
    des: "Nam tempus turpis at metus scelerisque placerat nulla deumantos solicitud felis. Pellentesque diam dolor, elementum etos lobortis des mollis ut risus. Sedcus faucibus an sullamcorper mattis drostique des commodo pharetras loremos.Donec pretium egestas sapien et mollis. Sample Unordered List Comodous in tempor ullamcorper miaculis Pellentesque vitae neque mollis urna mattis...",
    brand: "Aerosoles",
    movement: "High Heel",
    availability: "In Stock",
  },
  {
    id: 8,
    img1: "https://i.ibb.co/T0Mzjyk/sandals13.webp",
    img2: "https://i.ibb.co/VqhMcBt/sandals10.webp",
    img3: "https://i.ibb.co/Nm46235/sandals4.webp",
    name: "Synthetic Leather Sandal",
    price: "84.00",
    des: "Nam tempus turpis at metus scelerisque placerat nulla deumantos solicitud felis. Pellentesque diam dolor, elementum etos lobortis des mollis ut risus. Sedcus faucibus an sullamcorper mattis drostique des commodo pharetras loremos.Donec pretium egestas sapien et mollis. Sample Unordered List Comodous in tempor ullamcorper miaculis Pellentesque vitae neque mollis urna mattis...",
    brand: "Aerosoles",
    movement: "High Heel",
    availability: "In Stock",
  },
];

// Featured Collection Data
export const FeatureCollectionData = [
  {
    id: 8,
    img1: "https://i.ibb.co/jfDxZqy/clothing9.webp",
    img2: "https://i.ibb.co/nbFdsSZ/clothing1.webp",
    img3: "https://i.ibb.co/PwtZK73/clothing3.webp",
    name: "Skin tight Jeans & Tees",
    price: "740",
    des: "Nam tempus turpis at metus scelerisque placerat nulla deumantos solicitud felis. Pellentesque diam dolor, elementum etos lobortis des mollis ut risus. Sedcus faucibus an sullamcorper mattis drostique des commodo pharetras loremos.Donec pretium egestas sapien et mollis. Sample Unordered List Comodous in tempor ullamcorper miaculis Pellentesque vitae neque mollis urna mattis...",
    brand: "Gucci",
    movement: "Western Dress",
    availability: "In Stock",
  },
  {
    id: 7,
    img1: "https://i.ibb.co/7k7t509/handbags13.webp",
    img2: "https://i.ibb.co/6HsLY6N/handbags2.webp",
    img3: "https://i.ibb.co/MDXyKyF/handbags7.webp",
    name: "Cross Body Handbag",
    price: "75.00",
    des: "Nam tempus turpis at metus scelerisque placerat nulla deumantos solicitud felis. Pellentesque diam dolor, elementum etos lobortis des mollis ut risus. Sedcus faucibus an sullamcorper mattis drostique des commodo pharetras loremos.Donec pretium egestas sapien et mollis. Sample Unordered List Comodous in tempor ullamcorper miaculis Pellentesque vitae neque mollis urna mattis...",
    brand: "Lifestyle",
    movement: "Bags",
    availability: "In Stock",
  },
  {
    id: 7,
    img1: "https://i.ibb.co/Nm46235/sandals4.webp",
    img2: "https://i.ibb.co/p2Xvg9P/sandals3.webp",
    img3: "https://i.ibb.co/2Fg3MYy/sandals5.webp",
    name: "Open Toe Stiletto",
    price: "75.00",
    des: "Nam tempus turpis at metus scelerisque placerat nulla deumantos solicitud felis. Pellentesque diam dolor, elementum etos lobortis des mollis ut risus. Sedcus faucibus an sullamcorper mattis drostique des commodo pharetras loremos.Donec pretium egestas sapien et mollis. Sample Unordered List Comodous in tempor ullamcorper miaculis Pellentesque vitae neque mollis urna mattis...",
    brand: "Aerosoles",
    movement: "High Heel",
    availability: "In Stock",
  },
  {
    id: 6,
    img1: "https://i.ibb.co/MDXyKyF/handbags7.webp",
    img2: "https://i.ibb.co/pfdKq5D/handbags9.webp",
    img3: "https://i.ibb.co/1sZWJSX/handbags1.jpg",
    name: "Flap Satchel Bag",
    price: "67.00",
    des: "Nam tempus turpis at metus scelerisque placerat nulla deumantos solicitud felis. Pellentesque diam dolor, elementum etos lobortis des mollis ut risus. Sedcus faucibus an sullamcorper mattis drostique des commodo pharetras loremos.Donec pretium egestas sapien et mollis. Sample Unordered List Comodous in tempor ullamcorper miaculis Pellentesque vitae neque mollis urna mattis...",
    brand: "Lifestyle",
    movement: "Hand Bag",
    availability: "In Stock",
  },
  {
    id: 2,
    img1: "https://i.ibb.co/8Kgxm03/clothing4.webp",
    img2: "https://i.ibb.co/B3CLbD9/clothing5.webp",
    img3: "https://i.ibb.co/nD98Y7p/clothing6.webp",
    name: "Jeans & Tee full sleeves",
    price: "789.00",
    des: "Nam tempus turpis at metus scelerisque placerat nulla deumantos solicitud felis. Pellentesque diam dolor, elementum etos lobortis des mollis ut risus. Sedcus faucibus an sullamcorper mattis drostique des commodo pharetras loremos.Donec pretium egestas sapien et mollis. Sample Unordered List Comodous in tempor ullamcorper miaculis Pellentesque vitae neque mollis urna mattis...",
    brand: "Salvatore",
    movement: "T-Shirt",
    availability: "In Stock",
  },
  {
    id: 8,
    img1: "https://i.ibb.co/MDXyKyF/handbags7.webp",
    img2: "https://i.ibb.co/rbXvdJy/handbags10.webp",
    img3: "https://i.ibb.co/pdz19VJ/handbags5.webp",
    name: "Handbags",
    price: "84.00",
    des: "Nam tempus turpis at metus scelerisque placerat nulla deumantos solicitud felis. Pellentesque diam dolor, elementum etos lobortis des mollis ut risus. Sedcus faucibus an sullamcorper mattis drostique des commodo pharetras loremos.Donec pretium egestas sapien et mollis. Sample Unordered List Comodous in tempor ullamcorper miaculis Pellentesque vitae neque mollis urna mattis...",
    brand: "Gucci",
    movement: "Hand Bag",
    availability: "In Stock",
  },
  {
    id: 4,
    img1: "https://i.ibb.co/1sZWJSX/handbags1.jpg",
    img2: "https://i.ibb.co/CQ00dTn/handbags15.webp",
    img3: "https://i.ibb.co/StN8hnN/handbags14.webp",
    name: "Shoulder Strap Handbags",
    price: "45.00",
    des: "Nam tempus turpis at metus scelerisque placerat nulla deumantos solicitud felis. Pellentesque diam dolor, elementum etos lobortis des mollis ut risus. Sedcus faucibus an sullamcorper mattis drostique des commodo pharetras loremos.Donec pretium egestas sapien et mollis. Sample Unordered List Comodous in tempor ullamcorper miaculis Pellentesque vitae neque mollis urna mattis...",
    brand: "Salvatore",
    movement: "Bags",
    availability: "In Stock",
  },
];
